#!/bin/bash
# cp git-hooks/pre-push .git/hooks/pre-push; chmod 700 .git/hooks/pre-push

protected_branch='master'

commits=`git log @{u}..`

current_branch=`git symbolic-ref HEAD | awk -F'/' '{print $NF}'`

if [ $current_branch == $protected_branch ]; then
    exit 1
fi

exit 0

# vim: set fenc=utf8 expandtab sw=4 ts=4:
